sudo: required
services:
    - docker

before_install:
    - docker build -t urbanzpolski/docker-react -f Dockerfile .

script:
    - docker run urbanzpolski/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "eu-west-1"
    app: "docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-eu-west-1-498164689280"
    bucket_path: "docker"
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
        secure: "$AWS_SECRET_KEY"


        
        
        